In [1]:
import numpy as np

In [2]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [3]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [4]:
array1 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [5]:
booleans = np.array([True, True, False, True, True, False, True, True, True, False, True])

In [6]:
np.where(boolean)

NameError: name 'boolean' is not defined

In [7]:
np.where(booleans)

(array([ 0,  1,  3,  4,  6,  7,  8, 10], dtype=int64),)

In [8]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [9]:
np.where(array1 > 4)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [10]:
filter = np.where(array1 > 4)

In [11]:
array1(filter)

TypeError: 'numpy.ndarray' object is not callable

In [12]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])