In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

B = np.random.rand(3, 3)

In [3]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [4]:
B

array([[0.20338387, 0.99805966, 0.69897837],
       [0.00406004, 0.41515529, 0.97680389],
       [0.18814621, 0.14159987, 0.20668305]])

In [5]:
A + B

array([[ 1.20338387e+00, -1.94033693e-03,  2.69897837e+00],
       [ 3.00406004e+00,  2.41515529e+00,  2.97680389e+00],
       [ 4.18814621e+00,  1.14159987e+00,  2.20668305e+00]])

In [6]:
5 * A

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [7]:
np.dot(A, B)

array([[0.57561625, 0.86610411, 0.13554058],
       [0.99456411, 4.1076893 , 4.463909  ],
       [1.19388793, 4.69059368, 4.18608349]])

In [8]:
A @ B

array([[0.57561625, 0.86610411, 0.13554058],
       [0.99456411, 4.1076893 , 4.463909  ],
       [1.19388793, 4.69059368, 4.18608349]])

In [9]:
A @ B + (A + 2 * B)

array([[1.98238398, 1.86222344, 3.53349733],
       [4.0026842 , 6.93799988, 8.41751678],
       [5.57018036, 5.97379342, 6.59944958]])