In [1]:
import numpy as np

In [3]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [4]:
B = np.array([
    [0, 1],
    [-1, 3],
    [5, 2]
])
B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [5]:
C = np.random.rand(3, 5)
C

array([[0.48732954, 0.94438903, 0.41425438, 0.3299341 , 0.61720385],
       [0.65273142, 0.46776141, 0.83986877, 0.19585269, 0.80336991],
       [0.83231097, 0.54982958, 0.45941002, 0.91780876, 0.29712666]])

In [6]:
D = np.zeros((2, 4))
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [8]:
A[0][2]

2

In [9]:
A[0][5]

IndexError: index 5 is out of bounds for axis 0 with size 3