In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

In [3]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [4]:
A_tranpose = np.transpose(A)

In [5]:
A_tranpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [6]:
A_tranpose = A.T

In [7]:
A_tranpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [8]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
A @ I

array([[ 1., -1.,  2.],
       [ 3.,  2.,  2.],
       [ 4.,  1.,  2.]])

In [10]:
A_inverse = np.linalg.pinv(A)
A_inverse

array([[-0.2, -0.4,  0.6],
       [-0.2,  0.6, -0.4],
       [ 0.5,  0.5, -0.5]])

In [11]:
A @ A_inverse

array([[ 1.00000000e+00,  6.66133815e-16, -1.11022302e-15],
       [-2.22044605e-16,  1.00000000e+00, -6.66133815e-16],
       [ 0.00000000e+00,  2.22044605e-16,  1.00000000e+00]])